### ISSUE TITLE
Holes vs indels

### ISSUE THREAD

**Issue by lenecho** [swainechen/GBS-SBG#1]
Hi,
Great work. Would it be possible to list your definition of a hole in the README? It was listed in my output when I ran the typing through srst2.

**Comment by swainechen** [comment]
Hi, thanks for the feedback.

Holes are a term that SRST2 uses and basically are where there is no coverage on the allele. The definitive docs for that though should be the SRST2 docs:
https://github.com/katholt/srst2#output-files
You can check under the description for the "mismatches" column.

I'll also drop some extra text and a link in the readme for GBS-SBG about where to look for these types of things.

Thanks!

**Comment by lenecho** [comment]
Thanks, that cleared things up :).
